### PR TITLE
Skip generated columns in copy_rows method

### PR DESCRIPTION
**Pull request by Ceda**
I have same issue like #40 this PR detect generated columns from schema and prevent inserting.
Is working for Postgres, same issue for MySQL here #28

### CODE REVIEW

**Comment by bricct** [comment]
This looks good except for one small problem and that is that some Identity columns can be generated.  

There are two cases for generated identity columns
`GENERATED BY DEFAULT` and `GENERATED ALWAYS`

The latter of which causes problems by making insert statements fail.  With your branch the statements would no longer fail but the generated ID columns would be generated by Postgres and thus break referential integrity.

In the case that an `IDENTITY` column is `GENERATED BY DEFAULT` the column should not be ignored and should simply be inserted as normal.

In the case that an `IDENTITY` column is `GENERATED ALWAYS` the insert statement should have `OVERRIDING SYSTEM VALUE` following the column list e.g.  
```
INSERT INTO user 
     (id, name, password) 
OVERRIDING SYSTEM VALUE 
VALUES
      (1, 'user', 'password123');
```

An identity columns' generated status can be discerned via the `pg_attribute.attidentity` field. 
This field can be one of three values: 

- the zero byte '' by default, 
- 'a' if it is `GENERATED ALWAYS`
- or 'd' if it is `GENERATED BY DEFAULT`

I'll do my best to include these changes in my free-time but feel free to take care of it yourself as well. Thank you!

**Comment by bricct** [comment]
I have made a PR off of your PR that will add the requested changes that I commented. Once you merge that PR, I can merge this one as well. Thanks!

[Link to PR](https://github.com/Ceda/condenser/pull/1)

**Comment by Ceda** [comment]
> I have made a PR off of your PR that will add the requested changes that I commented. Once you merge that PR, I can merge this one as well. Thanks!
> 
> [Link to PR](https://github.com/Ceda/condenser/pull/1)

Nice work, thank you... I squashed your code into my branch...

**Comment by bricct** [comment]
Thank you @Ceda !

**Pull request merged**
